- activity/activity_pool.go
- activity/plugin.go
- client/plugin.go
- tests/src/Workflow/CancelSignalledChildWorkflow.php
- tests/src/Workflow/CancelledMidflightWorkflow.php
- tests/src/Workflow/CancelledNestedWorkflow.php
- tests/src/Workflow/CancelledScopeWorkflow.php
- tests/src/Workflow/CancelledSingleScopeWorkflow.php
- tests/src/Workflow/CancelledWithCompensationWorkflow.php
- tests/src/Workflow/ParallelScopesWorkflow.php
- tests/worker.php
- workflow/plugin.go
closes #26 
1. Fix the return type of the `Workers` method in the activities plugin. `SyncWorker` -> `BaseProcess`
2. Fix PHP tests according to the latest `sdk-php` dev-master.
~- [ ] Any user-facing changes are mentioned in `CHANGELOG.md`.~
> Bug(activities): Workers method return type for the informer plugin

- CHANGELOG.md
- go.mod
- go.sum
- tests/docker-compose.yaml
RC.2 Roadrunner-temporal release
- Update `docker-compose.yaml`, use `postgres` instead of `cassandra`.
- Endure update to v1.0.0-RC.2
- Roadrunner core update to v2.0.0-RC.3 (ref: [release](https://github.com/spiral/roadrunner/releases/tag/v2.0.0-RC.3))
> release(RC.2): RC.2 Release

- workflow/process.go
The current implementation does not pass the failure to the workflow log. Instead, it uses the legacy "Message" field with an additional prefix which does not play well in Temporal UI.
The panic message now passed explicitly to the workflow engine and log without any extra modifications. The failure message converted using the default FailureToError function provided by Temporal. No user changes.
~- [ ] All commits in this PR are signed (`git commit -s`).~
> feat(protocol): Explicitly pass panic message

- CHANGELOG.md
- tests/src/Workflow/CancelledMidflightWorkflow.php
- workflow/process.go
closes #42 
-🪛 use `runCommand` instead of `pushCommand`
> 🐛 bug(process:close): Run command directly instead of pushing it to the queue

- activity/activity_pool.go
- workflow/worker.go
closes: #73 
- Increase timeout to 10 days (inf in terms of processing workers tasks).
> bug(timeout): increase workflow pool timeout

- CHANGELOG.md
- tests/child_test.go
- tests/src/Workflow/WithChild2Workflow.php
- workflow/process.go
closes https://github.com/temporalio/sdk-php/issues/113
Properly pass the error to the underlying PHP worker.
> bug(workflow): fixes the bug causing the panic on temporal client when child workflow id can not be allocated

- go.mod
- go.sum
- plugin.go
closes: https://github.com/roadrunner-server/roadrunner/issues/1249
- Overwrite `client-name` and `client-version`
> feat: overwrite `client-name` and `client-version`

- aggregatedpool/handler.go
- internal/protocol.go
https://github.com/temporalio/sdk-php/issues/76
Same functionality like in GO-SDK - https://github.com/temporalio/samples-go/tree/main/searchattributes
Changes needed in PHP-SDK - https://github.com/temporalio/sdk-php/pull/248
Added missing implementation of `UpsertWorkflowSearchAttributes` command.
Changes: https://github.com/roadrunner-server/rr-e2e-tests/pull/138
Workflow file: https://github.com/temporalio/sdk-php/blob/6a40e81ba7125ee32fbb242599f65ddff649500a/tests/Fixtures/src/Workflow/UpsertSearchAttributesWorkflow.php
Also definition of search attributes needs to be executed to test server before running workflow - https://github.com/temporalio/sdk-php/blob/6a40e81ba7125ee32fbb242599f65ddff649500a/tests/SearchAttributeTestInvoker.php
By submitting this pull request, I confirm that …
> feat: upsert search attributes

- aggregatedpool/handler.go
- go.mod
- go.sum
- internal/protocol.go
- Update deps.
- Remove deprecated methods.
- Remove `WorkflowExecutionTimeout` from the `ContinueAsNew`.
> chore: remove deprecated methods

- aggregatedpool/activity.go
- aggregatedpool/fns.go
- aggregatedpool/handler.go
- aggregatedpool/local_activity.go
- aggregatedpool/workflow.go
- go.mod
- go.sum
- plugin.go
- queue/queue.go
- WorkflowDefinition refactoring
- Move LocalActivityFn to the separate structure
- Protect MessageQueue with mutex
- Add more logs
> chore: workflow refactoring

- aggregatedpool/workers.go
- common/interfaces.go
- go.mod
- go.sum
- plugin.go
https://github.com/roadrunner-server/roadrunner/issues/1313
Possibility to use custom interceptors for Temporal.
> feature: interceptors plugins support

- common/interfaces.go
- go.mod
- go.sum
- workers_manager.go
ref: https://github.com/roadrunner-server/roadrunner/issues/1728
- New AddWorker/RemoveWorker feature support.
> chore: workers manager

- go.work.sum
- status.go
- tests/configs/.rr-status.yaml
- tests/go.mod
- tests/go.sum
- tests/plugin_status_test.go
closes: https://github.com/roadrunner-server/roadrunner/issues/1872
Added code to check status for status plugin.
> feature: implement status

- status.go
- Workflow pool doesn't need to be checked in status.
- Replace Workflow pool with Activity.
> fix: use activity pool instead of workflow

- .vscode/settings.json
- aggregatedpool/handler.go
- aggregatedpool/local_activity.go
- aggregatedpool/workflow.go
- internal.go
- internal/protocol.go
closes: https://github.com/roadrunner-server/roadrunner/issues/1940
- WF pool was incorrectly used to execute Local Activities.
- Update implementation, use the general pool for A + LA.
- Use LA execute function directly, w/o constructor like in prev. implementation.
- Add `headers` to the `execute` function (passed to the worker).
> fix: use LA pool for the local activities execution

- config.go
- schema.json
Adjust error messages
Add documented defaults for FlushBytes
Following my work in the roadrunner org where I've been moving all JSON schemas to the repos they belong to, here is that same change for temporal.
Added JSON schema.
Adjusted some error messages (syntax, grammar) and added default values according to documentation.
> feat: Add JSON schema, adjust documentation and defaults

- schema.json
type property is missing from metrics object.
Added type property to metrics object.
> chore: Fix JSON schema strict validation error

- schema.json
There's a problem with the if-else logic in the schema here.
I replaced if-else with a oneOf for a valid combination of options. I have tested this locally so it should be the last PR for this repo.
Also, `address` is not required. I looked at the driver and it defaults to `localhost:7233`. I changed it only for consistency with the prometheus package; I'm aware localhost and 127.0.0.1 is the same.
> chore: Fix broken if-else logic in JSON schema

- .github/workflows/linux.yml
- config.go
- tests/configs/.rr-h2c.yaml
- tests/env/docker-compose-temporal.yaml
- tests/env/h2c.yaml
- tests/general/h2c_test.go
- tls.go
In case of h2c there a no need to provide certificates with enabled TLS option
If TLS is enabled certificates files are optional.
> feature(h2c): optional certificates for TLS

- tests/configs/.rr-disable-activity-worker.yaml
- tests/general/general_test.go
https://github.com/temporalio/roadrunner-temporal/pull/598
Status trying to allocate same port for multiple tests
> fix: port allocation in status tests
